### ISSUE TITLE
The bug of deciding NTL version in HElib.

### ISSUE THREAD

**Issue by NanXiao** [bristolcrypto/HEAT#4]
Now, the HEAT's [HElib](https://github.com/shaih/HElib/tree/dd451770f2885aa22e6f1498143a18917e15bc26) has a bug in [NumbTh.h](https://github.com/shaih/HElib/blob/dd451770f2885aa22e6f1498143a18917e15bc26/src/NumbTh.h#L52-L55):  

```
// Test for the "right version" of NTL (currently 9.4.0)
#if ((NTL_MAJOR_VERSION<9)||(NTL_MINOR_VERSION<4)||(NTL_REVISION<0))
#error "This version of HElib requires NTL version 9.4.0 or above"
#endif
```

If the `NTL`'s version is `10.3.0`, `Helib` will also report error. So I think `HEAT` should use the newest [HElib](https://github.com/NanXiao/HElib) in which the [NumbTh.h](https://github.com/NanXiao/HElib/blob/15020f500cacfc41b610d81af4ea13d701893637/src/NumbTh.h#L53-L56) has been changed:  

```
// Test for the "right version" of NTL (currently 9.4.0)
#if ((NTL_MAJOR_VERSION<9)||(NTL_MAJOR_VERSION==9 && NTL_MINOR_VERSION<4))
#error "This version of HElib requires NTL version 9.4.0 or above"
#endif
```

**Comment by svivekv** [comment]
Note that HElib has been included as a git submodule and hence can be independently updated.

**Comment by NanXiao** [comment]
But if the user use ` git clone --recursive` command to clone `HEAT`, the [HElib](https://github.com/shaih/HElib/tree/dd451770f2885aa22e6f1498143a18917e15bc26) with the bug version will be cloned, and this `HElib` is not of a out-of-box product, and need to be updated to the newest `Helib`. I think this violates the original intention of `HEAT`.

Thanks!

**Comment by svivekv** [comment]
Okay. Will fix this.
